spring:
  application:
    name: wald-shop-api
  datasource:
    url: jdbc:postgresql://localhost:5432/wald_shop
    username: postgres
    password: abc123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /api
